Revert "Fix slice indices failure."
adafruit/Adafruit_CircuitPython_Pypixelbuf pull request #32
Opened 2021-06-05 02:59 UTC by dunkmann00

Now that indices are once again enabled in CP ([#4857](https://github.com/adafruit/circuitpython/pull/4857)), revert the changes from #31.

Tested with an itsybitsy M0.

2021-06-10 18:53 UTC, dunkmann00 commented
@kattni Have you had a chance to look at this?

2021-06-10 19:04 UTC, kattni commented
@dunkmann00 Unless I'm missing something, the CircuitPython change is not present in the current stable version of CircuitPython, 6.3.0. This means anyone using the stable version would still run into this bug. Until 7.0.0 is stable, we should not revert this change.

2021-06-10 19:56 UTC, dunkmann00 commented
@kattni In CP 6.x branches the change wasn't needed because the flag that turned off slice indices functionality didn't yet exist. This flag was introduced when the newer versions of micropython were merged into CP in the main branch. But since 6.3.0 didn't have this, indices should work just fine.

2021-06-10 19:58 UTC, kattni commented
@dunkmann00 Appreciate the follow-up. I'll test this out in the next day or two and get it merged if successful. Thanks for the fix!

2021-06-10 20:03 UTC, dunkmann00 commented
@kattni Np! I'll try to test it out myself as well.

2021-06-10 23:40 UTC, dunkmann00 commented
I can confirm this works on CP 6.3.0. Tested on an itsybitsy M0.

2021-06-18 18:45 UTC, dunkmann00 commented
Hey @kattni, just curious if you've had a chance to test this out on 6.3 yet?

2021-06-21 13:29 UTC, kattni commented
@dunkmann00 I have not. Apologies for the delay. I should have time this week.

2021-06-23 18:54 UTC, kattni approved these changes
Tested on QT Py M0 on both 6.3.0 and 7.0.0-alpha.3.

Thanks for the fix!

2021-06-23 18:57 UTC, kattni requested changes
Actually, I just tested it with a basic slice, upon remembering that was the original issue, and it fails with the same error.

@dunkmann00 Thoughts?

On 7.0.0-alpha.3:
```
import board
import neopixel

pixel = neopixel.NeoPixel(board.NEOPIXEL, 1)

while True:
    pixel[0:1] = (255, 0, 0) * 1
```
Fails with:
```AttributeError: 'slice' object has no attribute 'indices'```

2021-06-23 19:01 UTC, kattni commented
The slice code above works on 6.3.0 with this PR, but it turns the LED blue.

2021-06-23 19:16 UTC, dunkmann00 commented
> Actually, I just tested it with a basic slice, upon remembering that was the original issue, and it fails with the same error.
> @dunkmann00 Thoughts?

Thats actually kind of funny. It appears the change missed making it into 7.0.0-alpha-3 by about 10 hours 😆. So if you build from the tip of the main branch, it will be in there.

> The slice code above works on 6.3.0 with this PR, but it turns the LED blue.

Not sure about that, I'll look into it. I wonder, do you see that same effect without this PR as well?

2021-06-23 19:19 UTC, kattni commented
I just pulled an adafruit_pypixelbuf.mpy out of a previous 6.x bundle folder, and yes the LED is still blue.

2021-06-23 19:25 UTC, dunkmann00 commented
Interesting, I don't have any neopixels with me at the moment so I'll look into it more later. One more question, does it only happen when you set them using a slice, or also when setting just one?

i.e.
`pixel[0:1] = (255, 0, 0) * 1`  - Result: Blue LED
AND
`pixel[0] = (255, 0, 0)`  - Result: ?

As another thought, I wonder if this is a board specific problem?

2021-06-23 19:27 UTC, kattni commented
Setting a single pixel with `[0]` results in red.

2021-06-23 19:38 UTC, dunkmann00 commented
@kattni  I think you just need:
`pixel[0:1] = ((255, 0, 0)) * 1`
Because then it is a tuple of tuples, rather than a tuple of integers.

2021-06-23 19:57 UTC, kattni commented
@dunkmann00 Actually it's supposed to be `[(255, 0, 0)]`, if I bothered to look up what I was doing and not try to do LED slices on the fly (I never get it right on the first try). 

The blue LED was my fault. So that's not an issue. 

However, I still need to test it on `main`. I would like to hold off on merging this until we do another 7 alpha release if that's necessary, because otherwise it won't work properly with both releases available on circuitpython.org.

2021-06-23 20:04 UTC, dunkmann00 commented
Sounds good to me!

2021-07-12 21:49 UTC, kattni approved these changes
Tested with 7.0.0-alpha.4 successfully!

2021-07-12 21:49 UTC, merged